# import = [
#   "/usr/lib/node_modules/alacritty-themes/themes/3024.dark.toml"
# ]

[font]
size = 16

[font.normal]
family = "Inconsolata"
style = "Regular"

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.italic]
family = "Inconsolata"
style = "Italic"
